In [2]:
import streamlit as st
import pandas as pd
from langchain_openai import ChatOpenAI, OpenAI
from langchain_core.messages import HumanMessage, AIMessage, SystemMessage
import dotenv
import os
from langchain.agents.agent_types import AgentType
from langchain_experimental.agents.agent_toolkits import create_pandas_dataframe_agent
import matplotlib
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("C:/Users/pbcon/Downloads/test.csv")
df

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [4]:
dotenv.load_dotenv(".env", override=True)

llm = ChatOpenAI(model="gpt-3.5-turbo", api_key=os.environ['OPEN_AI_API'])
agent = create_pandas_dataframe_agent(
llm = llm, agent_type='tool-calling', df=df, verbose=True, allow_dangerous_code=True, return_intermediate_steps=True)

In [5]:
agent

AgentExecutor(verbose=True, agent=RunnableMultiActionAgent(runnable=RunnableAssign(mapper={
  agent_scratchpad: RunnableLambda(lambda x: message_formatter(x['intermediate_steps']))
})
| ChatPromptTemplate(input_variables=['agent_scratchpad', 'input'], input_types={'agent_scratchpad': typing.List[typing.Union[langchain_core.messages.ai.AIMessage, langchain_core.messages.human.HumanMessage, langchain_core.messages.chat.ChatMessage, langchain_core.messages.system.SystemMessage, langchain_core.messages.function.FunctionMessage, langchain_core.messages.tool.ToolMessage]]}, messages=[SystemMessage(content='\nYou are working with a pandas dataframe in Python. The name of the dataframe is `df`.\nThis is the result of `print(df.head())`:\n|    |   PassengerId |   Pclass | Name                                         | Sex    |   Age |   SibSp |   Parch |   Ticket |    Fare |   Cabin | Embarked   |\n|---:|--------------:|---------:|:---------------------------------------------|:-------|------:|--------:|--------:|---------:|--------:|--------:|:-----------|\n|  0 |           892 |        3 | Kelly, Mr. James                             | male   |  34.5 |       0 |       0 |   330911 |  7.8292 |     nan | Q          |\n|  1 |           893 |        3 | Wilkes, Mrs. James (Ellen Needs)             | female |  47   |       1 |       0 |   363272 |  7      |     nan | S          |\n|  2 |           894 |        2 | Myles, Mr. Thomas Francis                    | male   |  62   |       0 |       0 |   240276 |  9.6875 |     nan | Q          |\n|  3 |           895 |        3 | Wirz, Mr. Albert                             | male   |  27   |       0 |       0 |   315154 |  8.6625 |     nan | S          |\n|  4 |           896 |        3 | Hirvonen, Mrs. Alexander (Helga E Lindqvist) | female |  22   |       1 |       1 |  3101298 | 12.2875 |     nan | S          |'), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['input'], template='{input}')), MessagesPlaceholder(variable_name='agent_scratchpad')])
| RunnableBinding(bound=ChatOpenAI(client=<openai.resources.chat.completions.Completions object at 0x00000270FD20BBF0>, async_client=<openai.resources.chat.completions.AsyncCompletions object at 0x00000270FD241850>, openai_api_key=SecretStr('**********'), openai_proxy=''), kwargs={'tools': [{'type': 'function', 'function': {'name': 'python_repl_ast', 'description': 'A Python shell. Use this to execute python commands. Input should be a valid python command. When using this tool, sometimes output is abbreviated - make sure it does not look abbreviated before using it in your answer.', 'parameters': {'type': 'object', 'properties': {'query': {'description': 'code snippet to run', 'type': 'string'}}, 'required': ['query']}}}]})
| ToolsAgentOutputParser(), input_keys_arg=['input'], return_keys_arg=['output'], stream_runnable=True), tools=[PythonAstREPLTool(locals={'df':      PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James
1            893       3              Wilkes, Mrs. James (Ellen Needs)
2            894       2                     Myles, Mr. Thomas Francis
3            895       3                              Wirz, Mr. Albert
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)
..           ...     ...                                           ...
413         1305       3                            Spector, Mr. Woolf
414         1306       1                  Oliva y Ocana, Dona. Fermina
415         1307       3                  Saether, Mr. Simon Sivertsen
416         1308       3                           Ware, Mr. Frederick
417         1309       3                      Peter, Master. Michael J

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked
0      male  34.5      0      0              330911    7.8292   NaN        Q
1    female  47.0      1      0              363272    7.0000   NaN        S
2      male  62.0      0      0              240276    9.6875   NaN        Q
3      male  27.0      0      0              315154    8.6625   NaN        S
4    female  22.0      1      1             3101298   12.2875   NaN        S
..      ...   ...    ...    ...                 ...       ...   ...      ...
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S
414  female  39.0      0      0            PC 17758  108.9000  C105        C
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S
416    male   NaN      0      0              359309    8.0500   NaN        S
417    male   NaN      1      1                2668   22.3583   NaN        C

[418 rows x 11 columns]})], return_intermediate_steps=True)

In [6]:
agent.invoke("plot the price")

> Entering new AgentExecutor chain...

Invoking: `python_repl_ast` with `{'query': 'import matplotlib.pyplot as plt'}`
responded: To plot the fare price, we first need to import the necessary libraries and then create a simple plot using matplotlib. Let's proceed with this.


Invoking: `python_repl_ast` with `{'query': "df['Fare'].plot(kind='hist', bins=20, color='skyblue', edgecolor='black')\nplt.title('Fare Price Distribution')\nplt.xlabel('Fare Price')\nplt.ylabel('Frequency')\nplt.show()"}`
responded: To plot the fare price, we first need to import the necessary libraries and then create a simple plot using matplotlib. Let's proceed with this.

<string>:1: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown

Here is the histogram plot showing the distribution of fare prices in the dataset.

The x-axis represents the fare price, and the y-axis represents the frequency of each fare price.

> Finished chain.

{'input': 'plot the price',
 'output': 'Here is the histogram plot showing the distribution of fare prices in the dataset. \n\nThe x-axis represents the fare price, and the y-axis represents the frequency of each fare price.',
 'intermediate_steps': [(ToolAgentAction(tool='python_repl_ast', tool_input={'query': 'import matplotlib.pyplot as plt'}, log="\nInvoking: `python_repl_ast` with `{'query': 'import matplotlib.pyplot as plt'}`\nresponded: To plot the fare price, we first need to import the necessary libraries and then create a simple plot using matplotlib. Let's proceed with this.\n\n", message_log=[AIMessageChunk(content="To plot the fare price, we first need to import the necessary libraries and then create a simple plot using matplotlib. Let's proceed with this.", additional_kwargs={'tool_calls': [{'index': 0, 'id': 'call_JlijyWzGTaNMvq5RShhWpr1A', 'function': {'arguments': '{"query": "import matplotlib.pyplot as plt"}', 'name': 'python_repl_ast'}, 'type': 'function'}, {'index': 1, 'id': 'call_ykpyZ4y0HoPVljOsShJQOeR0', 'function': {'arguments': '{"query": "df[\'Fare\'].plot(kind=\'hist\', bins=20, color=\'skyblue\', edgecolor=\'black\')\\nplt.title(\'Fare Price Distribution\')\\nplt.xlabel(\'Fare Price\')\\nplt.ylabel(\'Frequency\')\\nplt.show()"}', 'name': 'python_repl_ast'}, 'type': 'function'}]}, response_metadata={'finish_reason': 'tool_calls', 'model_name': 'gpt-3.5-turbo-0125'}, id='run-ae552d5a-58e1-4775-af0a-c51cdb281e96', tool_calls=[{'name': 'python_repl_ast', 'args': {'query': 'import matplotlib.pyplot as plt'}, 'id': 'call_JlijyWzGTaNMvq5RShhWpr1A', 'type': 'tool_call'}, {'name': 'python_repl_ast', 'args': {'query': "df['Fare'].plot(kind='hist', bins=20, color='skyblue', edgecolor='black')\nplt.title('Fare Price Distribution')\nplt.xlabel('Fare Price')\nplt.ylabel('Frequency')\nplt.show()"}, 'id': 'call_ykpyZ4y0HoPVljOsShJQOeR0', 'type': 'tool_call'}], tool_call_chunks=[{'name': 'python_repl_ast', 'args': '{"query": "import matplotlib.pyplot as plt"}', 'id': 'call_JlijyWzGTaNMvq5RShhWpr1A', 'index': 0, 'type': 'tool_call_chunk'}, {'name': 'python_repl_ast', 'args': '{"query": "df[\'Fare\'].plot(kind=\'hist\', bins=20, color=\'skyblue\', edgecolor=\'black\')\\nplt.title(\'Fare Price Distribution\')\\nplt.xlabel(\'Fare Price\')\\nplt.ylabel(\'Frequency\')\\nplt.show()"}', 'id': 'call_ykpyZ4y0HoPVljOsShJQOeR0', 'index': 1, 'type': 'tool_call_chunk'}])], tool_call_id='call_JlijyWzGTaNMvq5RShhWpr1A'),
   ''),
  (ToolAgentAction(tool='python_repl_ast', tool_input={'query': "df['Fare'].plot(kind='hist', bins=20, color='skyblue', edgecolor='black')\nplt.title('Fare Price Distribution')\nplt.xlabel('Fare Price')\nplt.ylabel('Frequency')\nplt.show()"}, log='\nInvoking: `python_repl_ast` with `{\'query\': "df[\'Fare\'].plot(kind=\'hist\', bins=20, color=\'skyblue\', edgecolor=\'black\')\\nplt.title(\'Fare Price Distribution\')\\nplt.xlabel(\'Fare Price\')\\nplt.ylabel(\'Frequency\')\\nplt.show()"}`\nresponded: To plot the fare price, we first need to import the necessary libraries and then create a simple plot using matplotlib. Let\'s proceed with this.\n\n', message_log=[AIMessageChunk(content="To plot the fare price, we first need to import the necessary libraries and then create a simple plot using matplotlib. Let's proceed with this.", additional_kwargs={'tool_calls': [{'index': 0, 'id': 'call_JlijyWzGTaNMvq5RShhWpr1A', 'function': {'arguments': '{"query": "import matplotlib.pyplot as plt"}', 'name': 'python_repl_ast'}, 'type': 'function'}, {'index': 1, 'id': 'call_ykpyZ4y0HoPVljOsShJQOeR0', 'function': {'arguments': '{"query": "df[\'Fare\'].plot(kind=\'hist\', bins=20, color=\'skyblue\', edgecolor=\'black\')\\nplt.title(\'Fare Price Distribution\')\\nplt.xlabel(\'Fare Price\')\\nplt.ylabel(\'Frequency\')\\nplt.show()"}', 'name': 'python_repl_ast'}, 'type': 'function'}]}, response_metadata={'finish_reason': 'tool_calls', 'model_name': 'gpt-3.5-turbo-0125'}, id='run-ae552d5a-58e1-4775-af0a-c51cdb281e96', tool_calls=[{'name': 'python_repl_ast', 'args': {'query': 'import matplotlib.pyplot as plt'}, 'id': 'call_JlijyWzGTaNMvq5RShhWpr1A', 'type': 'tool_call'}, {'name': 'python_repl_ast', 'args': {'query': "df['Fare'].plot(kind='hist', bins=20, color='skyblue', edgecolor='black')\nplt.title('Fare Price Distribution')\nplt.xlabel('Fare Price')\nplt.ylabel('Frequency')\nplt.show()"}, 'id': 'call_ykpyZ4y0HoPVljOsShJQOeR0', 'type': 'tool_call'}], tool_call_chunks=[{'name': 'python_repl_ast', 'args': '{"query": "import matplotlib.pyplot as plt"}', 'id': 'call_JlijyWzGTaNMvq5RShhWpr1A', 'index': 0, 'type': 'tool_call_chunk'}, {'name': 'python_repl_ast', 'args': '{"query": "df[\'Fare\'].plot(kind=\'hist\', bins=20, color=\'skyblue\', edgecolor=\'black\')\\nplt.title(\'Fare Price Distribution\')\\nplt.xlabel(\'Fare Price\')\\nplt.ylabel(\'Frequency\')\\nplt.show()"}', 'id': 'call_ykpyZ4y0HoPVljOsShJQOeR0', 'index': 1, 'type': 'tool_call_chunk'}])], tool_call_id='call_ykpyZ4y0HoPVljOsShJQOeR0'),
   '')]}

In [7]:
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')
plt.bar(df.Sex, height=500)
plt.show()

C:\Users\pbcon\AppData\Local\Temp\ipykernel_36376\1226233169.py:4: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()